GET http://localhost:3000

### Get all notes
GET http://localhost:3000/api/notes

### Get single note
GET http://localhost:3000/api/notes/4

### Get single nonexisting note
GET http://localhost:3000/api/notes/nonexistingid

### Delete note
DELETE http://localhost:3000/api/notes/1

### Create note
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "content": "node.js is also cool"
}