GET http://localhost:3000

### Get all notes
GET http://localhost:3000/api/notes

### Get single note
GET http://localhost:3000/api/notes/669fb91dd2a9ba472da74ee8

### Get single nonexisting note
GET http://localhost:3000/api/notes/669fb91dd2a9ba472da74ee7

### Delete note
DELETE http://localhost:3000/api/notes/669fab9669330fe1799ecd72

### Create note
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "content": "node.js is also cool"
}

### Test unknown endpoint
GET http://localhost:3000/not/found