GET http://localhost:3000

### Get all notes
GET http://localhost:3000/api/notes

### Get single note
GET http://localhost:3000/api/notes/66acebd05616cd15dbefe3fe

### Get single nonexisting note
GET http://localhost:3000/api/notes/669fb91dd2a9ba472da74ee7

### Try to get single note with invalid id
GET http://localhost:3000/api/notes/1

### Delete note
DELETE http://localhost:3000/api/notes/669fab9669330fe1799ecd72

### Create note
POST http://localhost:3000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im16ZWxpbmthIiwiaWQiOiI2NmEzYTQ2OWFjMWM3YjFmYzlmN2I2OTciLCJpYXQiOjE3MjI2MDg1NDR9.LYYkJTYOAwO4PKAIq9WOo38cpeKKxcdbHJtRp3MFN-s

{
  "content": "Single page apps use token based auth",
  "important": false
}

### Update note
PUT http://localhost:3000/api/notes/669fad878eab5fa0dcdfd8d0
Content-Type: application/json

{
  "important": true
}

### Test unknown endpoint
GET http://localhost:3000/not/found