GET http://localhost:3000

### Get all notes
GET http://localhost:3000/api/notes

### Get single note
GET http://localhost:3000/api/notes/669fad878eab5fa0dcdfd8d0

### Get single nonexisting note
GET http://localhost:3000/api/notes/669fb91dd2a9ba472da74ee7

### Try to get single note with invalid id
GET http://localhost:3000/api/notes/1

### Delete note
DELETE http://localhost:3000/api/notes/669fab9669330fe1799ecd72

### Create note
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "userId": "66a3a469ac1c7b1fc9f7b697",
  "content": "The existing code and test need to be changed when user id added to system"
}

### Update note
PUT http://localhost:3000/api/notes/669fad878eab5fa0dcdfd8d0
Content-Type: application/json

{
  "important": true
}

### Test unknown endpoint
GET http://localhost:3000/not/found